---
- name: Mount Exchange 2019 ISO
  community.windows.win_disk_image:
    image_path: "{{ ludus_exchange_iso_directory }}\\{{ ludus_exchange_iso_url.split('/') | last }}"
    state: present
  register: iso_mount
  when: ludus_os_version in ["2019", "2022"]

- name: Mount Exchange 2016 ISO
  community.windows.win_disk_image:
    image_path: "{{ ludus_exchange_iso_directory }}\\{{ ludus_exchange2016_iso_url.split('/') | last }}"
    state: present
  register: iso_mount
  when: ludus_os_version == "2016"

- name: Prepare Schema
  ansible.windows.win_shell: |
    & {{ iso_mount.mount_paths[0] }}Setup.exe /IAcceptExchangeServerLicenseTerms /PrepareSchema
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ludus_exchange_domain_username }}"
    ansible_become_password: "{{ ludus_exchange_domain_password }}"

- name: Prepare Active Directory
  ansible.windows.win_shell: |
    & {{ iso_mount.mount_paths[0] }}Setup.exe /IAcceptExchangeServerLicenseTerms /PrepareAD /OrganizationName:"{{ ludus_exchange_domain }}"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ludus_exchange_domain_username }}"
    ansible_become_password: "{{ ludus_exchange_domain_password }}"

- name: Install Exchange
  ansible.windows.win_shell: |
    & {{ iso_mount.mount_paths[0] }}Setup.exe /IAcceptExchangeServerLicenseTerms /Mode:Install /Role:Mailbox
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ludus_exchange_domain_username }}"
    ansible_become_password: "{{ ludus_exchange_domain_password }}"

- name: Unmount Exchange 2019 ISO
  community.windows.win_disk_image:
    image_path: "{{ ludus_exchange_iso_directory }}\\{{ ludus_exchange_iso_url.split('/') | last }}"
    state: absent
  when: ludus_os_version in ["2019", "2022"]  

- name: Unmount Exchange 2016 ISO
  community.windows.win_disk_image:
    image_path: "{{ ludus_exchange_iso_directory }}\\{{ ludus_exchange2016_iso_url.split('/') | last }}"
    state: absent
  when: ludus_os_version == "2016"  


- name: Remove Exchange 2019 ISO file
  ansible.windows.win_file:
    path: "{{ ludus_exchange_iso_directory }}\\{{ ludus_exchange_iso_url.split('/') | last }}"
    state: absent
  when: ludus_os_version in ["2019", "2022"]  

- name: Remove Exchange 2016 ISO file
  ansible.windows.win_file:
    path: "{{ ludus_exchange_iso_directory }}\\{{ ludus_exchange2016_iso_url.split('/') | last }}"
    state: absent
  when: ludus_os_version == "2016"  

