- name: Check if Exchange is installed
  win_service:
    name: "MSExchangeFrontendTransport"
  register: exchange_installed

- name: End the play if Exchange is already installed
  ansible.builtin.meta: end_host
  when: exchange_installed.exists

- name: Run PowerShell command to get Windows Server version
  ansible.windows.win_shell: |
    $osInfo = Get-WmiObject Win32_OperatingSystem
    $osInfo.Caption
  register: windows_server_caption

- name: Set fact for Windows Server 2019
  set_fact:
    is_windows_server_2019: "{{ 'Windows Server 2019' in windows_server_caption.stdout }}"
  when: windows_server_caption is defined

- name: Set fact for Windows Server 2016
  set_fact:
    is_windows_server_2016: "{{ 'Windows Server 2016' in windows_server_caption.stdout }}"
  when: windows_server_caption is defined

- name: Download Exchange ISO for Windows Server 2016
  ansible.builtin.include_tasks: ludus-download-exchange-2016.yml
  when: is_windows_server_2016

- name: Download Exchange ISO for Windows Server 2019
  ansible.builtin.include_tasks: ludus-download-exchange-2019.yml
  when: is_windows_server_2019

- name: Ludus Exchange Server features to be installed
  ansible.builtin.include_tasks: ludus-exchange-pre.yml

- name: Install Exchange Server
  ansible.builtin.include_tasks: ludus-exchange-install.yml